"""
EU Cosmetics Regulation 1223/2009 — Hardcoded ingredient database.
Covers Annex II (prohibited), Annex III (restricted), Annex V (preservatives),
Annex VI (UV filters), and the 26 declared fragrance allergens.

All concentration limits are in % (w/w) unless otherwise noted.
"""

from typing import Dict, Any, Optional

# ── Annex V — Permitted preservatives ─────────────────────────────────────────

PRESERVATIVES: Dict[str, Dict[str, Any]] = {
    "phenoxyethanol": {
        "inci": "Phenoxyethanol",
        "cas": "122-99-6",
        "status": "restricted",
        "annex": "V",
        "entry": "29",
        "max_conc": {"general": 1.0, "rinse_off": 1.0, "leave_on": 1.0, "oral": None, "eye": 1.0, "spray": 1.0, "sunscreen": 1.0},
        "conditions": "Max 1.0% in all cosmetic products. Not permitted in products for children under 3 years (except bath products, shampoos, and rinse-off products).",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Conservante molto comune nei cosmetici. Permesso fino all'1%. Ci sono però restrizioni per i prodotti destinati ai bambini sotto i 3 anni.",
    },
    "methylparaben": {
        "inci": "Methylparaben",
        "cas": "99-76-3",
        "status": "restricted",
        "annex": "V",
        "entry": "12",
        "max_conc": {"general": 0.4, "rinse_off": 0.4, "leave_on": 0.4, "oral": 0.4, "eye": 0.4, "spray": 0.4, "sunscreen": 0.4},
        "conditions": "Max 0.4% as acid (single ester). Max 0.8% as acid (total mixture of esters). Not to be used in products for children under 3 years intended for the nappy area.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Parabene di metile, uno dei conservanti più usati. Permesso allo 0.4% da solo o 0.8% in miscela con altri parabeni. Vietato nei prodotti per le zone del pannolino nei bambini under 3.",
    },
    "ethylparaben": {
        "inci": "Ethylparaben",
        "cas": "120-47-8",
        "status": "restricted",
        "annex": "V",
        "entry": "12",
        "max_conc": {"general": 0.4, "rinse_off": 0.4, "leave_on": 0.4, "oral": 0.4, "eye": 0.4, "spray": 0.4, "sunscreen": 0.4},
        "conditions": "Max 0.4% as acid (single ester). Max 0.8% as acid (total mixture of esters).",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Parabene di etile. Stesse regole del Methylparaben: max 0.4% da solo, 0.8% in miscela.",
    },
    "propylparaben": {
        "inci": "Propylparaben",
        "cas": "94-13-3",
        "status": "restricted",
        "annex": "V",
        "entry": "12",
        "max_conc": {"general": 0.14, "rinse_off": 0.14, "leave_on": 0.14, "oral": 0.14, "eye": 0.14, "spray": 0.14, "sunscreen": 0.14},
        "conditions": "Max 0.14% as acid (single ester). Max 0.8% total combined with Methylparaben and Ethylparaben. Not to be used in products for children under 3 years.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Parabene di propile. Limite più basso degli altri parabeni: max 0.14% da solo. Non usare nei prodotti per bambini under 3.",
    },
    "butylparaben": {
        "inci": "Butylparaben",
        "cas": "94-26-8",
        "status": "restricted",
        "annex": "V",
        "entry": "12",
        "max_conc": {"general": 0.14, "rinse_off": 0.14, "leave_on": 0.14, "oral": 0.14, "eye": 0.14, "spray": 0.14, "sunscreen": 0.14},
        "conditions": "Max 0.14% as acid (single ester). Max 0.8% total combined with Methylparaben and Ethylparaben. Not to be used in products for children under 3 years.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Parabene di butile. Stesse restrizioni del Propylparaben. Max 0.14% e vietato nei prodotti per bambini under 3.",
    },
    "benzyl_alcohol": {
        "inci": "Benzyl Alcohol",
        "cas": "100-51-6",
        "status": "restricted",
        "annex": "V",
        "entry": "34",
        "max_conc": {"general": 1.0, "rinse_off": 1.0, "leave_on": 1.0, "oral": None, "eye": 1.0, "spray": 1.0, "sunscreen": 1.0},
        "conditions": "Max 1.0% when used as preservative. Also listed as fragrance allergen (EU 26 list) — must be declared on label >0.01% leave-on / >0.1% rinse-off.",
        "function": ["preservative", "fragrance", "solvent"],
        "eu_status": "permitted",
        "plain_explanation": "Alcol benzilico: può essere usato come conservante (max 1%) ma è anche un allergene da profumeria da dichiarare in etichetta sopra certi livelli.",
    },
    "benzoic_acid": {
        "inci": "Benzoic Acid",
        "cas": "65-85-0",
        "status": "restricted",
        "annex": "V",
        "entry": "1",
        "max_conc": {"general": 0.5, "rinse_off": 2.5, "leave_on": 0.5, "oral": 1.7, "eye": 0.5, "spray": 0.5, "sunscreen": 0.5},
        "conditions": "Rinse-off products max 2.5%. Other products max 0.5%. Oral hygiene max 1.7% (as acid). Must not be used in products for children under 3 years (oral hygiene products).",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Acido benzoico, conservante naturale. Limiti diversi a seconda del tipo di prodotto: max 2.5% per i risciacquabili, 0.5% per i leave-on.",
    },
    "sorbic_acid": {
        "inci": "Sorbic Acid",
        "cas": "110-44-1",
        "status": "restricted",
        "annex": "V",
        "entry": "5",
        "max_conc": {"general": 0.6, "rinse_off": 0.6, "leave_on": 0.6, "oral": 0.6, "eye": 0.6, "spray": 0.6, "sunscreen": 0.6},
        "conditions": "Max 0.6% as acid.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Acido sorbico, conservante molto usato anche in campo alimentare. Permesso fino allo 0.6% nei cosmetici.",
    },
    "dmdm_hydantoin": {
        "inci": "DMDM Hydantoin",
        "cas": "6440-58-0",
        "status": "restricted",
        "annex": "V",
        "entry": "25",
        "max_conc": {"general": 0.6, "rinse_off": 0.6, "leave_on": 0.6, "oral": None, "eye": 0.6, "spray": 0.6, "sunscreen": 0.6},
        "conditions": "Max 0.6%. Formaldehyde releaser — must indicate 'contains formaldehyde' on label when concentration of formaldehyde in finished product exceeds 0.05%.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Conservante che rilascia formaldeide lentamente. Permesso al max 0.6%, ma se il prodotto finito contiene >0.05% di formaldeide bisogna dichiararlo in etichetta.",
    },
    "imidazolidinyl_urea": {
        "inci": "Imidazolidinyl Urea",
        "cas": "39236-46-9",
        "status": "restricted",
        "annex": "V",
        "entry": "26",
        "max_conc": {"general": 0.6, "rinse_off": 0.6, "leave_on": 0.6, "oral": None, "eye": 0.6, "spray": 0.6, "sunscreen": 0.6},
        "conditions": "Max 0.6%. Formaldehyde releaser — label warning if formaldehyde in finished product >0.05%.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Altro conservante rilasciatore di formaldeide. Stesso limite e stessa regola di etichettatura del DMDM Hydantoin.",
    },
    "chlorphenesin": {
        "inci": "Chlorphenesin",
        "cas": "104-29-0",
        "status": "restricted",
        "annex": "V",
        "entry": "35",
        "max_conc": {"general": 0.3, "rinse_off": 0.3, "leave_on": 0.3, "oral": None, "eye": None, "spray": 0.3, "sunscreen": 0.3},
        "conditions": "Max 0.3%. Not to be used in products for children under 3 years.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Conservante con attività antifungina. Max 0.3%, non usare nei prodotti per bambini under 3.",
    },
    "sodium_benzoate": {
        "inci": "Sodium Benzoate",
        "cas": "532-32-1",
        "status": "restricted",
        "annex": "V",
        "entry": "1",
        "max_conc": {"general": 0.5, "rinse_off": 2.5, "leave_on": 0.5, "oral": 1.7, "eye": 0.5, "spray": 0.5, "sunscreen": 0.5},
        "conditions": "Salt of Benzoic Acid — same restrictions apply.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Sale dell'acido benzoico. Ha le stesse restrizioni dell'acido benzoico: max 2.5% per i risciacquabili, 0.5% per leave-on.",
    },
    "dehydroacetic_acid": {
        "inci": "Dehydroacetic Acid",
        "cas": "520-45-6",
        "status": "restricted",
        "annex": "V",
        "entry": "7",
        "max_conc": {"general": 0.6, "rinse_off": 0.6, "leave_on": 0.6, "oral": None, "eye": None, "spray": 0.6, "sunscreen": 0.6},
        "conditions": "Max 0.6% as acid. Not to be used in aerosols (sprays). Not for use in products intended for mucous membranes.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Conservante organico. Permesso al max 0.6%, ma non negli spray aerosol e nei prodotti per mucose.",
    },
    "mit": {
        "inci": "Methylisothiazolinone",
        "cas": "2682-20-4",
        "status": "restricted",
        "annex": "V",
        "entry": "39",
        "max_conc": {"general": None, "rinse_off": 0.0015, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "ONLY permitted in rinse-off products at max 0.0015% (15 ppm). PROHIBITED in all leave-on products since 2017. Not permitted in products for children under 3 years.",
        "function": ["preservative"],
        "eu_status": "restricted",
        "plain_explanation": "MIT è un conservante potente ma molto allergenico. Dal 2017 è vietato nei prodotti leave-on (creme, lozioni). Ammesso solo nei risciacquabili a concentrazioni molto basse (0.0015% = 15 ppm).",
    },
    "cmit": {
        "inci": "Methylchloroisothiazolinone",
        "cas": "26172-55-4",
        "status": "restricted",
        "annex": "V",
        "entry": "39",
        "max_conc": {"general": None, "rinse_off": 0.0015, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "CMIT/MIT mixture (3:1) — max 0.0015% in rinse-off products only. PROHIBITED in all leave-on products.",
        "function": ["preservative"],
        "eu_status": "restricted",
        "plain_explanation": "CMIT si usa sempre in combinazione con MIT. Stessa regola: solo nei risciacquabili a max 0.0015%, vietato nei leave-on.",
    },
    "sodium_hydroxymethylglycinate": {
        "inci": "Sodium Hydroxymethylglycinate",
        "cas": "70161-44-3",
        "status": "restricted",
        "annex": "V",
        "entry": "30",
        "max_conc": {"general": 0.5, "rinse_off": 0.5, "leave_on": 0.5, "oral": None, "eye": None, "spray": 0.5, "sunscreen": 0.5},
        "conditions": "Max 0.5%. Formaldehyde releaser — label warning required if formaldehyde in finished product >0.05%.",
        "function": ["preservative"],
        "eu_status": "permitted",
        "plain_explanation": "Altro conservante che rilascia formaldeide. Max 0.5% con obbligo di dichiarazione in etichetta se il prodotto finito supera 0.05% di formaldeide.",
    },
}

# ── Annex III — Restricted substances ─────────────────────────────────────────

RESTRICTED_SUBSTANCES: Dict[str, Dict[str, Any]] = {
    "hydroquinone": {
        "inci": "Hydroquinone",
        "cas": "123-31-9",
        "status": "restricted",
        "annex": "III",
        "entry": "14",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Prohibited as skin-lightening agent in cosmetics for general use since 2001. Only permitted in nail products (hardeners) at max 0.02% after mixing for application. Hair dye formulations have specific restrictions.",
        "function": ["skin_conditioning", "hair_dye"],
        "eu_status": "restricted",
        "plain_explanation": "Idrochinone: potente agente schiarente della pelle. È VIETATO nei cosmetici ad uso generale (creme, lozioni, sieri). Ammesso solo in pochissimi casi specifici come gli induritori per unghie.",
    },
    "resorcinol": {
        "inci": "Resorcinol",
        "cas": "108-46-3",
        "status": "restricted",
        "annex": "III",
        "entry": "35",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 0.5, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Hair dye: max 0.5% after mixing for application. Label: 'Contains Resorcinol'. Not to be used as skin-lightening agent.",
        "function": ["hair_dye", "anti-dandruff"],
        "eu_status": "restricted",
        "plain_explanation": "Resorcinolo usato come colorante per capelli. Max 0.5% nelle tinture per capelli. Non può essere usato come agente schiarente della pelle.",
    },
    "triclosan": {
        "inci": "Triclosan",
        "cas": "3380-34-5",
        "status": "restricted",
        "annex": "V",
        "entry": "27",
        "max_conc": {"general": None, "rinse_off": 0.3, "leave_on": 0.3, "oral": 0.3, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Max 0.3%. Permitted only in: toothpaste, hand soap, body soap/shower gel, deodorant (non-spray), face powder and blemish concealer. PROHIBITED in all other product categories.",
        "function": ["preservative", "antimicrobial"],
        "eu_status": "restricted",
        "plain_explanation": "Triclosan è un antimicrobico. Ammesso al max 0.3% solo in pochi prodotti specifici (dentifrici, saponi per mani, deodoranti non spray). VIETATO in tutti gli altri cosmetici.",
    },
    "kojic_acid": {
        "inci": "Kojic Acid",
        "cas": "501-30-4",
        "status": "restricted",
        "annex": "III",
        "entry": "243",
        "max_conc": {"general": 1.0, "rinse_off": None, "leave_on": 1.0, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Max 1.0% in face care products and hand care products (leave-on). Not permitted in rinse-off products.",
        "function": ["skin_lightening"],
        "eu_status": "restricted",
        "plain_explanation": "Acido kojico: ingrediente schiarente di origine naturale (funghi). Permesso al max 1% solo nelle creme viso e mani (leave-on). Non usare nei risciacquabili.",
    },
    "hydrogen_peroxide": {
        "inci": "Hydrogen Peroxide",
        "cas": "7722-84-1",
        "status": "restricted",
        "annex": "III",
        "entry": "8",
        "max_conc": {"general": None, "rinse_off": 12.0, "leave_on": 4.0, "oral": 0.1, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Hair care: up to 12% H2O2 (rinse-off); Skin care: max 4% H2O2; Nail hardeners: max 2% H2O2; Oral hygiene: max 0.1%. Must not be used in eye products. Label warnings required.",
        "function": ["hair_bleaching", "teeth_whitening", "nail_hardening"],
        "eu_status": "restricted",
        "plain_explanation": "Perossido di idrogeno (acqua ossigenata). Usato per schiarire i capelli, sbiancare i denti. Limiti molto variabili: fino al 12% nei prodotti per capelli, max 0.1% per l'igiene orale. Vietato negli occhi.",
    },
    "formaldehyde": {
        "inci": "Formaldehyde",
        "cas": "50-00-0",
        "status": "restricted",
        "annex": "V",
        "entry": "13",
        "max_conc": {"general": 0.2, "rinse_off": 0.2, "leave_on": 0.2, "oral": 0.1, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Max 0.2% (as HCHO) in products. Max 0.1% in oral hygiene. PROHIBITED in aerosols. Label 'contains formaldehyde' required when >0.05%.",
        "function": ["preservative"],
        "eu_status": "restricted",
        "plain_explanation": "Formaldeide: conservante molto efficace ma tossico e allergizzante. Permesso a concentrazioni molto basse (max 0.2%). Vietato negli spray. Obbligo di dichiarazione in etichetta.",
    },
    "bha": {
        "inci": "BHA",
        "cas": "25013-16-5",
        "status": "restricted",
        "annex": "III",
        "entry": "160",
        "max_conc": {"general": 0.5, "rinse_off": 0.5, "leave_on": 0.5, "oral": 0.5, "eye": 0.5, "spray": 0.5, "sunscreen": 0.5},
        "conditions": "Max 0.5%. Used as antioxidant.",
        "function": ["antioxidant"],
        "eu_status": "permitted",
        "plain_explanation": "BHA (butilato idrossianisolo) è un antiossidante che previene il deterioramento dei prodotti. Permesso al max 0.5%.",
    },
    "edta": {
        "inci": "Disodium EDTA",
        "cas": "139-33-3",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "No specific concentration limit in EU Cosmetics Regulation. Use at effective concentration (typically 0.01-0.1%).",
        "function": ["chelating_agent"],
        "eu_status": "permitted",
        "plain_explanation": "EDTA è un agente chelante che migliora l'efficacia di altri conservanti sequestrando i metalli. Non ha un limite specifico nell'UE, si usa alla concentrazione efficace (tipicamente 0.01-0.1%).",
    },
    "p_phenylenediamine": {
        "inci": "p-Phenylenediamine",
        "cas": "106-50-3",
        "status": "restricted",
        "annex": "III",
        "entry": "8",
        "max_conc": {"general": None, "rinse_off": 2.0, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Hair dye only. Max 2.0% after mixing for application. Oxidative hair colorants must carry warning labels. Must not be used on eyebrows or eyelashes.",
        "function": ["hair_dye"],
        "eu_status": "restricted",
        "plain_explanation": "PPD è il pigmento principale delle tinture per capelli ossidative. Max 2% nelle tinture. VIETATO per sopracciglia e ciglia. Etichette di avvertenza obbligatorie.",
    },
    "dihydroxyacetone": {
        "inci": "Dihydroxyacetone",
        "cas": "96-26-4",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "No specific restriction in EU Cosmetics Regulation. Use at safe and effective levels. Caution with spray/aerosol products (inhalation risk).",
        "function": ["skin_tanning"],
        "eu_status": "permitted",
        "plain_explanation": "DHA è l'agente abbronzante senza sole più usato. Non ha un limite specifico nell'UE. Attenzione agli spray: rischio di inalazione.",
    },
    "aluminum_chlorohydrate": {
        "inci": "Aluminum Chlorohydrate",
        "cas": "1327-41-9",
        "status": "restricted",
        "annex": "III",
        "entry": "49",
        "max_conc": {"general": None, "rinse_off": 6.25, "leave_on": 10.6, "oral": None, "eye": None, "spray": 6.25, "sunscreen": None},
        "conditions": "Antiperspirant: max 10.6% in leave-on; max 6.25% in spray/rinse-off. Not for use on broken or irritated skin. Not for use in intimate hygiene products.",
        "function": ["antiperspirant"],
        "eu_status": "restricted",
        "plain_explanation": "Cloridrato di alluminio: ingrediente attivo degli antitraspiranti. Permesso fino al 10.6% nei prodotti leave-on. Non usare su pelle irritata o lesa.",
    },
    "salicylic_acid": {
        "inci": "Salicylic Acid",
        "cas": "69-72-7",
        "status": "restricted",
        "annex": "III",
        "entry": "98",
        "max_conc": {"general": None, "rinse_off": 3.0, "leave_on": 2.0, "oral": 0.3, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Leave-on body care (excluding face): max 2%. Rinse-off hair care: max 3%. Oral hygiene: max 0.3%. Not for use in products for children under 3 years (except shampoos). Label: 'Contains Salicylic Acid'.",
        "function": ["preservative", "keratolytic", "exfoliant"],
        "eu_status": "restricted",
        "plain_explanation": "Acido salicilico: usato come esfoliante e anti-acne. Limiti diversi per tipo di prodotto: max 2% nei leave-on, 3% nei risciacquabili capelli, 0.3% nell'igiene orale. Non usare nei prodotti per bambini under 3.",
    },
    "zinc_pyrithione": {
        "inci": "Zinc Pyrithione",
        "cas": "13463-41-7",
        "status": "restricted",
        "annex": "V",
        "entry": "8",
        "max_conc": {"general": None, "rinse_off": 1.0, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Max 1.0% in rinse-off hair products only. Not permitted in leave-on products.",
        "function": ["preservative", "anti-dandruff"],
        "eu_status": "restricted",
        "plain_explanation": "Piritione di zinco: efficace contro la forfora. Permesso al max 1% SOLO nei prodotti per capelli risciacquabili (shampoo antiforfora). Vietato nei leave-on.",
    },
    "phenol": {
        "inci": "Phenol",
        "cas": "108-95-2",
        "status": "prohibited",
        "annex": "II",
        "entry": "1175",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "PROHIBITED in all cosmetic products.",
        "function": [],
        "eu_status": "prohibited",
        "plain_explanation": "Fenolo: VIETATO in tutti i cosmetici. È tossico per contatto e inalazione. Non può essere usato in nessun prodotto cosmetico.",
    },
    "lead_acetate": {
        "inci": "Lead Acetate",
        "cas": "301-04-2",
        "status": "prohibited",
        "annex": "II",
        "entry": "207",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "PROHIBITED in all cosmetic products.",
        "function": [],
        "eu_status": "prohibited",
        "plain_explanation": "Acetato di piombo: VIETATO in tutti i cosmetici. Il piombo è un metallo pesante tossico accumulabile nell'organismo.",
    },
    "mercury_compounds": {
        "inci": "Mercury Compounds",
        "cas": "various",
        "status": "prohibited",
        "annex": "II",
        "entry": "221",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "PROHIBITED in all cosmetic products (as general rule). Exception: thiomersal in eye makeup at max 0.007%.",
        "function": [],
        "eu_status": "prohibited",
        "plain_explanation": "Composti del mercurio: generalmente VIETATI in tutti i cosmetici. Solo un'eccezione per il tiomersal nei cosmetici per occhi.",
    },
    "boric_acid": {
        "inci": "Boric Acid",
        "cas": "10043-35-3",
        "status": "restricted",
        "annex": "III",
        "entry": "163",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": None, "oral": None, "eye": None, "spray": None, "sunscreen": None},
        "conditions": "Max 0.7% in bath products. Not to be used in children's products. Not to be used as preservative.",
        "function": ["buffering_agent"],
        "eu_status": "restricted",
        "plain_explanation": "Acido borico: ammesso solo nei prodotti da bagno al max 0.7%. Non può essere usato come conservante e non va usato nei prodotti per bambini.",
    },
}

# ── Annex VI — UV filters ──────────────────────────────────────────────────────

UV_FILTERS: Dict[str, Dict[str, Any]] = {
    "avobenzone": {
        "inci": "Butyl Methoxydibenzoylmethane",
        "cas": "70356-09-1",
        "status": "restricted",
        "annex": "VI",
        "entry": "27",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 5.0, "oral": None, "eye": None, "spray": 5.0, "sunscreen": 5.0},
        "conditions": "Max 5.0% in sunscreen products.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Avobenzone (Parsol 1789): filtro solare chimico che assorbe i raggi UVA. Max 5% nei prodotti solari.",
    },
    "benzophenone_3": {
        "inci": "Benzophenone-3",
        "cas": "131-57-7",
        "status": "restricted",
        "annex": "VI",
        "entry": "4",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 6.0, "oral": None, "eye": None, "spray": 6.0, "sunscreen": 6.0},
        "conditions": "Max 6.0%. Max 0.5% when used for photo-protection only. Label: 'Contains Benzophenone-3'.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Benzofenone-3 (Oxybenzone): filtro UVA/UVB. Max 6% nei solari. Etichetta obbligatoria. Controverso per potenziale attività estrogenica.",
    },
    "octocrylene": {
        "inci": "Octocrylene",
        "cas": "6197-30-4",
        "status": "restricted",
        "annex": "VI",
        "entry": "10",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 10.0, "oral": None, "eye": None, "spray": 10.0, "sunscreen": 10.0},
        "conditions": "Max 10.0% in body lotions and creams; max 10.0% in sunscreens.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Octocrilene: filtro UVB molto stabile. Permesso fino al 10% nei prodotti solari. Spesso usato per stabilizzare altri filtri.",
    },
    "titanium_dioxide": {
        "inci": "Titanium Dioxide",
        "cas": "13463-67-7",
        "status": "restricted",
        "annex": "VI",
        "entry": "27",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 25.0, "oral": None, "eye": None, "spray": None, "sunscreen": 25.0},
        "conditions": "Max 25% in sunscreen products. NOT allowed in spray/powder products that could lead to inhalation of nanoparticles (nano-TiO2). Purity criteria apply.",
        "function": ["uv_filter", "colorant"],
        "eu_status": "permitted",
        "plain_explanation": "Biossido di titanio (TiO2): filtro minerale che riflette i raggi UV. Max 25% nei solari. La forma nanometrica NON può essere usata negli spray (rischio inalazione).",
    },
    "zinc_oxide": {
        "inci": "Zinc Oxide",
        "cas": "1314-13-2",
        "status": "restricted",
        "annex": "VI",
        "entry": "30",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 25.0, "oral": None, "eye": None, "spray": None, "sunscreen": 25.0},
        "conditions": "Max 25% in face products and products intended for application on small areas of the body.",
        "function": ["uv_filter", "astringent"],
        "eu_status": "permitted",
        "plain_explanation": "Ossido di zinco: filtro minerale a largo spettro UVA/UVB. Max 25%. Molto tollerato dalla pelle, ottimo per pelli sensibili.",
    },
    "tinosorb_m": {
        "inci": "Methylene Bis-Benzotriazolyl Tetramethylbutylphenol",
        "cas": "103597-45-1",
        "status": "restricted",
        "annex": "VI",
        "entry": "26",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 10.0, "oral": None, "eye": None, "spray": 10.0, "sunscreen": 10.0},
        "conditions": "Max 10.0%.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Tinosorb M: filtro solare a largo spettro disponibile solo nell'UE (non approvato FDA). Max 10%. Molto fotostabile.",
    },
    "tinosorb_s": {
        "inci": "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
        "cas": "187393-00-6",
        "status": "restricted",
        "annex": "VI",
        "entry": "25",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 10.0, "oral": None, "eye": None, "spray": 10.0, "sunscreen": 10.0},
        "conditions": "Max 10.0%.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Tinosorb S: filtro solare chimico a largo spettro, approvato solo in UE. Molto efficace contro UVA1 e fotostabile. Max 10%.",
    },
    "uvinul_a": {
        "inci": "Diethylamino Hydroxybenzoyl Hexyl Benzoate",
        "cas": "302776-68-7",
        "status": "restricted",
        "annex": "VI",
        "entry": "28",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 10.0, "oral": None, "eye": None, "spray": 10.0, "sunscreen": 10.0},
        "conditions": "Max 10.0%.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Uvinul A Plus: filtro UVA fotostabile, approvato in UE. Max 10%.",
    },
    "homosalate": {
        "inci": "Homosalate",
        "cas": "118-56-9",
        "status": "restricted",
        "annex": "VI",
        "entry": "3",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 7.34, "oral": None, "eye": None, "spray": 7.34, "sunscreen": 7.34},
        "conditions": "Max 7.34% (as homomenthyl salicylate).",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Omosalato: filtro UVB. Il limite è stato abbassato nel 2022 a 7.34% per preoccupazioni di sicurezza sistemica.",
    },
    "octyl_methoxycinnamate": {
        "inci": "Ethylhexyl Methoxycinnamate",
        "cas": "5466-77-3",
        "status": "restricted",
        "annex": "VI",
        "entry": "16",
        "max_conc": {"general": None, "rinse_off": None, "leave_on": 10.0, "oral": None, "eye": None, "spray": 10.0, "sunscreen": 10.0},
        "conditions": "Max 10.0%.",
        "function": ["uv_filter"],
        "eu_status": "permitted",
        "plain_explanation": "Octinoxate (OMC): filtro UVB tra i più usati al mondo. Max 10% nell'UE. Approvato anche dalla FDA ma con restrizioni nei reef protetti.",
    },
}

# ── EU 26 declared fragrance allergens ────────────────────────────────────────
# Thresholds for mandatory label declaration (% w/w):
#   leave_on: 0.001% (10 ppm)
#   rinse_off: 0.01% (100 ppm)
# After EU 2023 update, several new allergens have been added (47 total).
# This table covers the original 26.

FRAGRANCE_ALLERGENS_EU26: Dict[str, Dict[str, Any]] = {
    "linalool": {
        "inci": "Linalool",
        "cas": "78-70-6",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Linalolo: profumante naturale presente in lavanda, coriandolo. Deve essere dichiarato in etichetta se >0.001% nei leave-on o >0.01% nei risciacquabili.",
    },
    "limonene": {
        "inci": "Limonene",
        "cas": "5989-27-5",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Limonene: profumante naturale dal limone e agrumi. Dichiarazione obbligatoria in etichetta sopra le soglie.",
    },
    "geraniol": {
        "inci": "Geraniol",
        "cas": "106-24-1",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Geraniolo: profumante presente nella rosa e nelle bacche di loto. Allergene da dichiarare.",
    },
    "citronellol": {
        "inci": "Citronellol",
        "cas": "106-22-9",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Citronellolo: presente nella citronella e nella rosa. Allergene dichiarabile.",
    },
    "cinnamal": {
        "inci": "Cinnamal",
        "cas": "104-55-2",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Aldeide cinnamica: profumante con aroma di cannella. Allergene da dichiarare.",
    },
    "coumarin": {
        "inci": "Coumarin",
        "cas": "91-64-5",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Cumarina: profumante con aroma di vaniglia/fieno. Allergene, dichiarazione obbligatoria.",
    },
    "eugenol": {
        "inci": "Eugenol",
        "cas": "97-53-0",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Eugenolo: profumante del chiodi di garofano. Allergene dichiarabile.",
    },
    "benzyl_salicylate": {
        "inci": "Benzyl Salicylate",
        "cas": "118-58-1",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Salicilato di benzile: ingrediente floreale usato nelle fragranze. Allergene dichiarabile.",
    },
    "citral": {
        "inci": "Citral",
        "cas": "5392-40-5",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Citrale: profumante degli agrumi (limone, arancio). Allergene dichiarabile.",
    },
    "farnesol": {
        "inci": "Farnesol",
        "cas": "4602-84-0",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Farnesolo: presente nelle rose e nelle fragranze florali. Allergene dichiarabile.",
    },
    "hexyl_cinnamal": {
        "inci": "Hexyl Cinnamal",
        "cas": "101-86-0",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Aldeide alfa-amilcinnamica: profumante floreale (gelsomino). Allergene dichiarabile.",
    },
    "lilial": {
        "inci": "Butylphenyl Methylpropional",
        "cas": "80-54-6",
        "status": "prohibited",
        "threshold_leave_on": 0.0,
        "threshold_rinse_off": 0.0,
        "eu_status": "prohibited",
        "plain_explanation": "LILIAL (Butylphenyl Methylpropional): VIETATO in tutti i cosmetici dal marzo 2022 per preoccupazioni sulla tossicità riproduttiva (categoria Repr. 1B). La sua presenza in un prodotto lo rende non conforme.",
    },
    "isoeugenol": {
        "inci": "Isoeugenol",
        "cas": "97-54-1",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Isoeugenolo: strutturalmente simile all'eugenolo. Allergene dichiarabile.",
    },
    "anise_alcohol": {
        "inci": "Anise Alcohol",
        "cas": "105-13-5",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Alcol anisolico: profumante dell'anice. Allergene dichiarabile.",
    },
    "benzyl_benzoate": {
        "inci": "Benzyl Benzoate",
        "cas": "120-51-4",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Benzoato di benzile: profumante balsámico. Allergene dichiarabile.",
    },
    "benzyl_cinnamate": {
        "inci": "Benzyl Cinnamate",
        "cas": "103-41-3",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Cinamato di benzile: profumante balsámico. Allergene dichiarabile.",
    },
    "amyl_cinnamal": {
        "inci": "Amyl Cinnamal",
        "cas": "122-40-7",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Aldeide amilcinnamica: profumante floreale. Allergene dichiarabile.",
    },
    "amylcinnamyl_alcohol": {
        "inci": "Amylcinnamyl Alcohol",
        "cas": "101-85-9",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Alcol amilcinnamico: profumante floreale. Allergene dichiarabile.",
    },
    "cinnamyl_alcohol": {
        "inci": "Cinnamyl Alcohol",
        "cas": "104-54-1",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Alcol cinnamico: profumante speziato (cannella). Allergene dichiarabile.",
    },
    "alpha_isomethyl_ionone": {
        "inci": "Alpha-Isomethyl Ionone",
        "cas": "127-51-5",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Alfa-isometil ionone: profumante violaceo (iris). Allergene dichiarabile.",
    },
    "methyl_2_octynoate": {
        "inci": "Methyl 2-Octynoate",
        "cas": "111-12-6",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Metil 2-ottinato: profumante vegetale. Allergene dichiarabile.",
    },
    "evernia_prunastri": {
        "inci": "Evernia Prunastri Extract",
        "cas": "90028-68-5",
        "status": "restricted",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Estratto di lichene (Oak Moss): potente allergizzante naturale. Restrizioni severe in UE. Dichiarabile come allergene.",
    },
    "evernia_furfuracea": {
        "inci": "Evernia Furfuracea Extract",
        "cas": "90028-67-4",
        "status": "restricted",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Estratto di Tree Moss: allergene simile all'Oak Moss. Restrizioni severe in UE.",
    },
    "hydroxycitronellal": {
        "inci": "Hydroxycitronellal",
        "cas": "107-75-5",
        "status": "allergen",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Idrossicitronellale: profumante muguet/tiglio. Allergene dichiarabile.",
    },
    "oak_moss_absolute": {
        "inci": "Oak Moss Absolute",
        "cas": "90028-68-5",
        "status": "restricted",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Assoluto di lichene: usato nelle fragranze chypree. Grave allergizzante. Restrizioni severe IFRA e UE.",
    },
    "tree_moss_absolute": {
        "inci": "Tree Moss Absolute",
        "cas": "90028-67-4",
        "status": "restricted",
        "threshold_leave_on": 0.001,
        "threshold_rinse_off": 0.01,
        "eu_status": "declarable",
        "plain_explanation": "Assoluto di Tree Moss: allergene dichiarabile nelle fragranze.",
    },
}

# ── Additional common cosmetic ingredients (no restriction) ───────────────────

COMMON_PERMITTED: Dict[str, Dict[str, Any]] = {
    "glycerin": {
        "inci": "Glycerin",
        "cas": "56-81-5",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None},
        "conditions": "No restriction. GRAS humectant.",
        "function": ["humectant", "skin_conditioning"],
        "eu_status": "permitted",
        "plain_explanation": "Glicerina: umettante tra i più sicuri e usati. Nessuna restrizione nell'UE.",
    },
    "niacinamide": {
        "inci": "Niacinamide",
        "cas": "98-92-0",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None},
        "conditions": "No restriction. Used typically at 2-10%.",
        "function": ["skin_conditioning", "skin_brightening"],
        "eu_status": "permitted",
        "plain_explanation": "Niacinamide (Vitamina B3): ingrediente funzionale molto usato per pori dilatati, macchie, tono uniforme. Nessuna restrizione nell'UE.",
    },
    "retinol": {
        "inci": "Retinol",
        "cas": "68-26-8",
        "status": "restricted",
        "annex": "III",
        "entry": "339",
        "max_conc": {"general": None, "leave_on": 0.3, "rinse_off": 0.3, "sunscreen": None, "eye": 0.05},
        "conditions": "Max 0.3% in face/hand leave-on, max 0.3% in body lotion, max 0.05% around eye area. Not to be used in children under 3. Not to be used in body lotions intended to cover large skin areas. SPF products not recommended.",
        "function": ["skin_conditioning", "anti_aging"],
        "eu_status": "restricted",
        "plain_explanation": "Retinolo (Vitamina A): efficace anti-aging ma con restrizioni EU. Max 0.3% nella crema viso, max 0.05% intorno agli occhi. Non usare nei bambini under 3.",
    },
    "hyaluronic_acid": {
        "inci": "Sodium Hyaluronate",
        "cas": "9067-32-7",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None},
        "conditions": "No restriction.",
        "function": ["humectant", "skin_conditioning"],
        "eu_status": "permitted",
        "plain_explanation": "Acido ialuronico (Sodium Hyaluronate): potente umettante naturale. Nessuna restrizione nell'UE. Sicuro per tutti i tipi di pelle.",
    },
    "ascorbic_acid": {
        "inci": "Ascorbic Acid",
        "cas": "50-81-7",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None},
        "conditions": "No specific restriction. Used as antioxidant and skin brightener.",
        "function": ["antioxidant", "skin_brightening"],
        "eu_status": "permitted",
        "plain_explanation": "Vitamina C (acido ascorbico): antiossidante e schiarente. Nessuna restrizione nell'UE.",
    },
    "tocopherol": {
        "inci": "Tocopherol",
        "cas": "59-02-9",
        "status": "permitted",
        "annex": None,
        "entry": None,
        "max_conc": {"general": None},
        "conditions": "No specific restriction. Used as antioxidant.",
        "function": ["antioxidant"],
        "eu_status": "permitted",
        "plain_explanation": "Vitamina E (Tocoferolo): antiossidante. Nessuna restrizione nell'UE.",
    },
}

# ── Master index ───────────────────────────────────────────────────────────────

INGREDIENT_DB: Dict[str, Dict[str, Any]] = {
    **PRESERVATIVES,
    **RESTRICTED_SUBSTANCES,
    **UV_FILTERS,
    **FRAGRANCE_ALLERGENS_EU26,
    **COMMON_PERMITTED,
}

# Also build a lookup by CAS number
CAS_INDEX: Dict[str, str] = {}
for key, data in INGREDIENT_DB.items():
    cas = data.get("cas")
    if cas and cas != "various":
        CAS_INDEX[cas] = key
